### ISSUE TITLE
Objects Tracker Api

### ISSUE THREAD

**Issue by ravyrafael** [ravyrafael/backend-aquinosburger#2]
- [x] Objects Tracker Api
  - [x] Create object -Ravy
  - [x] List Objects - Ravy
  - [x] Update Object - Klenner
  - [x] Find Object - Ravy
  - [x] Delete Object - Ravy
